### ISSUE TITLE
installation problems / scrimmage

### ISSUE THREAD

**Issue by palbers** [crichardson332/homebrew#9]
brew tap crichardson332/crich_brews
==> Tapping crichardson332/crich_brews
Cloning into '/usr/local/Homebrew/Library/Taps/crichardson332/homebrew-crich_brews'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 2), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/crichardson332/homebrew-crich_brews/Formula/rapidxml.rb
Calling needs :cxx14 is disabled! There is no replacement.
Please report this to the crichardson332/crich_brews tap:
  /usr/local/Homebrew/Library/Taps/crichardson332/homebrew-crich_brews/Formula/rapidxml.rb:17

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/crichardson332/homebrew-crich_brews/Formula/vtk@6.2.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the crichardson332/crich_brews tap:
  /usr/local/Homebrew/Library/Taps/crichardson332/homebrew-crich_brews/Formula/vtk@6.2.rb:32

Error: Cannot tap crichardson332/crich_brews: invalid syntax in tap!

See there is something related back in November ...

**Comment by crichardson332** [comment]
It looks like those compiler checks have been deprecated in homebrew. The latest master has been updated to reflect those changes.
